"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "header.cta": "Contact Us",

    // Hero
    "hero.title": "AI-Powered Software.",
    "hero.titleSub": "Enterprise-Grade Delivery.",
    "hero.description": "Production-ready software at record speed. We combine AI agents, expert engineers, and proven processes to deliver secure, scalable solutions—from idea to launch in weeks, not months.",
    "hero.cta1": "Contact Us",
    "hero.cta2": "Request a Proposal",
    "hero.badge1": "On-prem",
    "hero.badge2": "SSO",
    "hero.badge3": "Arabic/English",
    "hero.badge4": "CI/CD",

    // Value Props
    "valueProps.title": "Why teams choose Cordoba AI",
    "valueProps.speed": "Speed, without shortcuts",
    "valueProps.speedDesc": "From idea to first release in weeks powered by AI agents and automation.",
    "valueProps.quality": "Quality you can trust",
    "valueProps.qualityDesc": "Code reviews, test coverage, and CI/CD gates.",
    "valueProps.security": "Security by design",
    "valueProps.securityDesc": "SSO, least-privilege access, encrypted secrets, audit logs.",
    "valueProps.scale": "Built to scale",
    "valueProps.scaleDesc": "Cloud or on-prem architectures for performance, reliability, and cost.",

    // Capabilities
    "capabilities.title": "What we build",
    "capabilities.digitalServices": "Digital Services & Portals",
    "capabilities.digitalServicesDesc": "Workflows, forms, SLAs, ePayments.",
    "capabilities.internalPlatforms": "Internal Platforms",
    "capabilities.internalPlatformsDesc": "Innovation, performance, PMO/portfolio, audits, HR workflows.",
    "capabilities.dataAI": "Data & AI",
    "capabilities.dataAIDesc": "Dashboards, ML/GenAI copilots, automations with AI agents.",
    "capabilities.integrations": "Integrations",
    "capabilities.integrationsDesc": "SAP, ESB/iPaaS, GRP/ERP, payment gateways.",
    "capabilities.mobileWeb": "Mobile & Web Apps",
    "capabilities.mobileWebDesc": "Responsive, accessible, bilingual (AR/EN).",

    // Process
    "process.title": "How we deliver—fast and safe",
    "process.discover": "Discover",
    "process.discoverDesc": "Scope, stakeholders, success metrics, and risk assessment.",
    "process.design": "Design",
    "process.designDesc": "UX wireframes, architecture blueprints, security requirements.",
    "process.build": "Build",
    "process.buildDesc": "AI-assisted development with expert engineers and daily progress updates.",
    "process.assure": "Assure",
    "process.assureDesc": "QA testing, security scans, performance benchmarks.",
    "process.launch": "Launch",
    "process.launchDesc": "Cutover planning, deployment, observability setup.",
    "process.evolve": "Evolve",
    "process.evolveDesc": "SLAs, optimizations, feature enhancements.",

    // Outcomes
    "outcomes.title": "Outcomes that matter",
    "outcomes.subtitle": "Proven delivery windows, reliability targets, and real speed gains—without compromising quality.",
    "outcomes.kpi1": "4–8 weeks",
    "outcomes.kpi1Desc": "to first production release",
    "outcomes.kpi2": ">99.9% uptime",
    "outcomes.kpi2Desc": "targets",
    "outcomes.kpi3": "30–50% faster",
    "outcomes.kpi3Desc": "delivery via AI agents + automation",
    "outcomes.quote": "Cordoba AI delivered our innovation platform in 6 weeks. Their AI-powered approach and expert team exceeded our expectations.",
    "outcomes.quoteAuthor": "Technology Director",

    // Featured Engagements
    "engagements.title": "Selected engagements",
    "engagements.learnMore": "Learn more",
    "engagements.portfolio": "Portfolio Manager",
    "engagements.portfolioDesc": "Enterprise portfolio & project governance with real-time visibility and control.",
    "engagements.portfolioBullet1": "Strategy alignment, prioritization & funding gates",
    "engagements.portfolioBullet2": "Health, risk & issue registers with workflows",
    "engagements.portfolioBullet3": "Cross-program roadmaps and executive dashboards",
    "engagements.ticketing": "Ticketing System",
    "engagements.ticketingDesc": "Modern IT/ops ticketing with SLAs, automation, and clear service reporting.",
    "engagements.ticketingBullet1": "Incident, service request & change workflows",
    "engagements.ticketingBullet2": "SLA policies, escalations, and email/MS Teams integration",
    "engagements.ticketingBullet3": "Knowledge base, categories, and analytics out of the box",
    "engagements.cms": "CMS (AI Website Builder — no dev needed)",
    "engagements.cmsDesc": "Create and publish pages using an AI agent—no coding. Secure, scalable, and fast.",
    "engagements.cmsBullet1": "Generate pages, sections, and media via prompts",
    "engagements.cmsBullet2": "Component library, themes, and on-brand style guardrails",
    "engagements.cmsBullet3": "Roles, approvals, SEO, and instant publishing",

    // CTA
    "cta.title": "Start your project with Cordoba AI",
    "cta.description": "Share your goals and we'll provide a delivery plan and timeline.",
    "cta.button": "Contact Us",

    // Contact Page
    "contact.title": "Get in touch",
    "contact.subtitle": "Tell us about your goals. We'll reply with a delivery plan and timeline.",
    "contact.badge1": "On-prem",
    "contact.badge2": "SSO",
    "contact.badge3": "Arabic/English",
    "contact.badge4": "CI/CD",
    "contact.name": "Full name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Work email",
    "contact.emailPlaceholder": "you@company.com",
    "contact.organization": "Organization",
    "contact.organizationPlaceholder": "Company / Entity",
    "contact.phone": "Phone (optional)",
    "contact.phonePlaceholder": "+971 ...",
    "contact.projectType": "Project type",
    "contact.projectTypePlaceholder": "Choose one",
    "contact.projectTypeOption1": "Portfolio Manager",
    "contact.projectTypeOption2": "Ticketing System",
    "contact.projectTypeOption3": "AI CMS (No-Dev Builder)",
    "contact.projectTypeOption4": "Other",
    "contact.message": "Message / goals",
    "contact.messagePlaceholder": "What do you want to build or improve?",
    "contact.attachment": "Attachment (optional)",
    "contact.attachmentHelper": "Upload brief / RFP (PDF, DOCX, ≤10MB)",
    "contact.consent": "I agree to be contacted about my request.",
    "contact.submit": "Send message",
    "contact.privacyNotice": "By submitting, you agree to our Privacy Policy.",
    "contact.successTitle": "Thanks—your request was received.",
    "contact.successMessage": "We'll respond within 1 business day.",
    "contact.referenceId": "Reference ID",
    "contact.infoTitle": "Contact Information",
    "contact.emailLabel": "Email",
    "contact.emailValue": "info@cordoba-ai.com",
    "contact.office": "Office",
    "contact.officeLocation": "Remote-first company (GMT+4)",
    "contact.followUs": "Follow us",
    "contact.businessHours": "Business hours",
    "contact.weekdays": "Monday – Friday",
    "contact.weekdaysTime": "9:00 AM – 6:00 PM (GMT+4)",
    "contact.weekend": "Saturday – Sunday",
    "contact.weekendTime": "Closed",

    // Footer
    "footer.company": "Company",
    "footer.about": "About",
    "footer.careers": "Careers",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.security": "Security",
    "footer.rights": "Cordoba AI - All rights reserved.",
    "footer.language": "Language",

    // Portfolio Manager Page
    "portfolio.hero.title": "Portfolio Manager",
    "portfolio.hero.subtitle": "Enterprise portfolio & project governance with real-time visibility and control.",
    "portfolio.hero.cta1": "Request a proposal",
    "portfolio.hero.cta2": "Book discovery call",
    "portfolio.pillars.title1": "Strategy → Delivery",
    "portfolio.pillars.desc1": "Link OKRs/strategic themes to programs, projects, and benefits.",
    "portfolio.pillars.title2": "Governance at speed",
    "portfolio.pillars.desc2": "Stage gates, DOA/RACI, and audit-ready change logs.",
    "portfolio.pillars.title3": "Truthful data",
    "portfolio.pillars.desc3": "Single source of truth for schedules, budgets, risks, and KPIs.",
    "portfolio.pillars.title4": "Executive clarity",
    "portfolio.pillars.desc4": "C-level dashboards and portfolio health in one view.",
    "portfolio.features.title": "What you get",
    "portfolio.features.planning": "Portfolio Planning",
    "portfolio.features.planningDesc": "Ideation intake, scoring models, prioritization, funding gates.",
    "portfolio.features.control": "Program/Project Control",
    "portfolio.features.controlDesc": "Milestones, dependencies, RAID logs, change requests.",
    "portfolio.features.financials": "Financials",
    "portfolio.features.financialsDesc": "CAPEX/OPEX, baselines, forecasts, and cost variance.",
    "portfolio.features.benefits": "Benefits & KPIs",
    "portfolio.features.benefitsDesc": "Targets vs actuals, benefit realization, initiative mapping.",
    "portfolio.features.resources": "Resources",
    "portfolio.features.resourcesDesc": "Roles, capacity, allocation heatmaps, workload.",
    "portfolio.features.reporting": "Reporting",
    "portfolio.features.reportingDesc": "Configurable dashboards, exports (PDF/XLS), auto briefings.",
    "portfolio.integrations.title": "Integrations",
    "portfolio.integrations.list": "SAP/Oracle/ERP • SSO (Entra ID/ADFS) • Email/Teams • Data warehouse/Power BI",
    "portfolio.howItWorks.title": "How it works",
    "portfolio.howItWorks.step1": "Discover & configure",
    "portfolio.howItWorks.step1Desc": "2–3 workshops",
    "portfolio.howItWorks.step2": "Import & map data",
    "portfolio.howItWorks.step2Desc": "Projects, resources, KPIs",
    "portfolio.howItWorks.step3": "Rollout & train",
    "portfolio.howItWorks.step3Desc": "Pilot → enterprise",
    "portfolio.outcomes.title": "Outcomes",
    "portfolio.outcomes.stat1": "30–50% faster",
    "portfolio.outcomes.stat1Desc": "reporting cycles",
    "portfolio.outcomes.stat2": "90% adoption",
    "portfolio.outcomes.stat2Desc": "within 8–12 weeks",
    "portfolio.outcomes.stat3": "25% reduction",
    "portfolio.outcomes.stat3Desc": "in unplanned slippage",
    "portfolio.useCases.title": "Use cases",
    "portfolio.useCases.gov": "Gov EPMO",
    "portfolio.useCases.strategy": "Strategy offices",
    "portfolio.useCases.it": "IT PMO",
    "portfolio.useCases.capital": "Capital projects",
    "portfolio.useCases.transformation": "Transformation programs",
    "portfolio.security.title": "Security & deployment",
    "portfolio.security.item1": "On-prem or sovereign cloud",
    "portfolio.security.item2": "SSO/MFA",
    "portfolio.security.item3": "Role-based access",
    "portfolio.security.item4": "Audit trails",
    "portfolio.cta.title": "Ready to govern with confidence?",
    "portfolio.cta.button": "Talk to an expert",
    "portfolio.faq.q1": "How do you handle complex DOA/RACI?",
    "portfolio.faq.a1": "We support multi-tier approval matrices, delegation rules, and custom RACI templates that map to your existing governance framework.",
    "portfolio.faq.q2": "Can we keep our existing tool and sync?",
    "portfolio.faq.a2": "Yes, we provide API and scheduled sync connectors for most project management tools, allowing hybrid operation during transition.",
    "portfolio.faq.q3": "How long to go live?",
    "portfolio.faq.a3": "Typical pilot deployment takes 4–8 weeks including discovery, configuration, data import, and user training.",
    "portfolio.faq.q4": "Do you support Arabic and RTL?",
    "portfolio.faq.a4": "Yes, full Arabic localization and RTL interface are included out of the box.",
    "portfolio.faq.q5": "What reports are included out of the box?",
    "portfolio.faq.a5": "Portfolio health dashboard, project status reports, financial variance, resource utilization, risk registers, and executive briefings.",

    // Ticketing System Page
    "ticketing.hero.title": "Ticketing System",
    "ticketing.hero.subtitle": "Modern IT/ops ticketing with SLAs, automation, and clear service reporting.",
    "ticketing.hero.cta1": "Start a pilot",
    "ticketing.hero.cta2": "See a demo",
    "ticketing.pillars.title1": "Resolve faster",
    "ticketing.pillars.desc1": "Guided forms, auto-routing, and smart suggestions.",
    "ticketing.pillars.title2": "No missed SLAs",
    "ticketing.pillars.desc2": "Policies, calendars, and multi-level escalations.",
    "ticketing.pillars.title3": "One knowledge base",
    "ticketing.pillars.desc3": "Articles, categories, and deflection analytics.",
    "ticketing.pillars.title4": "Built for ops",
    "ticketing.pillars.desc4": "Change & problem workflows, approvals, CAB support.",
    "ticketing.capabilities.title": "Capabilities",
    "ticketing.capabilities.types": "Ticket types",
    "ticketing.capabilities.typesDesc": "Incident, service request, problem, change.",
    "ticketing.capabilities.workflows": "Workflows",
    "ticketing.capabilities.workflowsDesc": "Intake forms, dynamic fields, approvals, assignment rules.",
    "ticketing.capabilities.slas": "SLAs",
    "ticketing.capabilities.slasDesc": "Clocks, pauses, holidays, breach notifications, escalation policies.",
    "ticketing.capabilities.channels": "Channels",
    "ticketing.capabilities.channelsDesc": "Portal, email parsing, MS Teams, API/webhooks.",
    "ticketing.capabilities.kb": "KB",
    "ticketing.capabilities.kbDesc": "Article authoring, versioning, feedback, search.",
    "ticketing.capabilities.analytics": "Analytics",
    "ticketing.capabilities.analyticsDesc": "SLA compliance, backlog aging, agent performance, CSAT.",
    "ticketing.automation.title": "Automation examples",
    "ticketing.automation.ex1": "Auto-assign based on category/impact",
    "ticketing.automation.ex2": "Suggest KB articles to requester/agent",
    "ticketing.automation.ex3": "Close stale tickets with reminders and safeguards",
    "ticketing.integrations.title": "Integrations",
    "ticketing.integrations.list": "Entra ID/ADFS • Email/SMTP • MS Teams • Asset/CMDB (optional) • Webhooks",
    "ticketing.timeline.title": "Implementation timeline",
    "ticketing.timeline.week1": "Week 1–2: discovery & catalog",
    "ticketing.timeline.week2": "Week 3–4: workflows & SLAs",
    "ticketing.timeline.week3": "Week 5–6: pilot & training",
    "ticketing.outcomes.title": "Outcomes",
    "ticketing.outcomes.stat1": "20–40% faster",
    "ticketing.outcomes.stat1Desc": "mean time to resolution",
    "ticketing.outcomes.stat2": "30% fewer",
    "ticketing.outcomes.stat2Desc": "reopens via better forms & KB",
    "ticketing.outcomes.stat3": "50%+ reduction",
    "ticketing.outcomes.stat3Desc": "in SLA breaches",
    "ticketing.cta.title": "Fix service chaos—start with a focused pilot",
    "ticketing.cta.button": "Start a pilot",
    "ticketing.faq.q1": "Do you migrate old tickets/KB?",
    "ticketing.faq.a1": "Yes, we provide migration tools and services to import historical tickets, attachments, and knowledge base articles while preserving relationships.",
    "ticketing.faq.q2": "How do holidays & business hours work in SLAs?",
    "ticketing.faq.a2": "You can define multiple calendars with holidays and business hours. SLA clocks pause outside business hours and auto-adjust for public holidays.",
    "ticketing.faq.q3": "Can requesters email directly?",
    "ticketing.faq.a3": "Yes, inbound email parsing creates tickets automatically, and replies sync bidirectionally between email and the portal.",
    "ticketing.faq.q4": "Do you support CAB/change calendar?",
    "ticketing.faq.a4": "Yes, change management includes CAB workflows, approval meetings, blackout windows, and calendar integration.",
    "ticketing.faq.q5": "What analytics are standard?",
    "ticketing.faq.a5": "SLA compliance rates, ticket volume trends, mean resolution time, backlog aging, agent workload, and customer satisfaction scores.",

    // AI CMS Page
    "cms.hero.title": "AI CMS (Website Builder — no dev needed)",
    "cms.hero.subtitle": "Create and publish pages using an AI agent—no coding. Secure, scalable, and fast.",
    "cms.hero.cta1": "Try the editor",
    "cms.hero.cta2": "Request a guided demo",
    "cms.pillars.title1": "Create by prompting",
    "cms.pillars.desc1": "Sections, pages, and media in minutes.",
    "cms.pillars.title2": "Always on-brand",
    "cms.pillars.desc2": "Themes, components, and style guardrails.",
    "cms.pillars.title3": "Governed publishing",
    "cms.pillars.desc3": "Roles, approvals, review flows, audit.",
    "cms.pillars.title4": "SEO built-in",
    "cms.pillars.desc4": "Metadata, sitemaps, and best-practice checks.",
    "cms.capabilities.title": "Capabilities",
    "cms.capabilities.ai": "AI editing",
    "cms.capabilities.aiDesc": "Block suggestions, rewrite/improve, extract summaries.",
    "cms.capabilities.components": "Components",
    "cms.capabilities.componentsDesc": "Hero, feature grids, CTA bands, FAQs, galleries, forms.",
    "cms.capabilities.media": "Media",
    "cms.capabilities.mediaDesc": "Image optimization, auto alt-text, CDN delivery.",
    "cms.capabilities.seo": "SEO",
    "cms.capabilities.seoDesc": "Titles/descriptions, schema, canonical, sitemap, redirects.",
    "cms.capabilities.localization": "Localization",
    "cms.capabilities.localizationDesc": "Arabic/English, RTL support, translation workflow.",
    "cms.capabilities.publishing": "Publishing",
    "cms.capabilities.publishingDesc": "Preview/compare, version history, instant rollback.",
    "cms.templates.title": "Templates",
    "cms.templates.gov": "Government service portal",
    "cms.templates.corporate": "Corporate site",
    "cms.templates.campaign": "Campaign/landing",
    "cms.security.title": "Security & access",
    "cms.security.item1": "SSO/MFA",
    "cms.security.item2": "Roles (author, editor, approver, admin)",
    "cms.security.item3": "Granular permissions",
    "cms.security.item4": "Audit logs",
    "cms.outcomes.title": "Outcomes",
    "cms.outcomes.stat1": "3–5× faster",
    "cms.outcomes.stat1Desc": "launch new pages",
    "cms.outcomes.stat2": "40–60% reduction",
    "cms.outcomes.stat2Desc": "in external development cost",
    "cms.outcomes.stat3": "Improved scores",
    "cms.outcomes.stat3Desc": "Core Web Vitals out of the box",
    "cms.cta.title": "Build your next page in minutes",
    "cms.cta.button": "Try the editor",
    "cms.faq.q1": "Can we import our current site/theme?",
    "cms.faq.a1": "Yes, we can migrate existing pages and adapt your brand theme into our component library during onboarding.",
    "cms.faq.q2": "How do approvals work?",
    "cms.faq.a2": "You define approval workflows by role/content type. Draft → Review → Approve → Publish, with notifications and comparison tools.",
    "cms.faq.q3": "Can non-technical teams manage Arabic/RTL?",
    "cms.faq.a3": "Absolutely. The AI editor and RTL preview work seamlessly for Arabic content without requiring technical knowledge.",
    "cms.faq.q4": "What about custom components?",
    "cms.faq.a4": "We can build custom components as part of onboarding or training your team to extend the library using our component SDK.",
    "cms.faq.q5": "Do you support on-prem deployment?",
    "cms.faq.a5": "Yes, the CMS can be deployed on-premises or in sovereign cloud environments with the same features as cloud SaaS.",
  },
  ar: {
    // Header
    "header.cta": "تواصل معنا",

    // Hero
    "hero.title": "برمجيات مدعومة بالذكاء الاصطناعي.",
    "hero.titleSub": "تسليم بمعايير مؤسسية.",
    "hero.description": "نطوّر برمجيات جاهزة للإنتاج بسرعة قياسية—من دون التنازل عن الأمان أو الجودة أو المعايير. نمزج بين عوامل الذكاء الاصطناعي والمهندسين الخبراء لبناء أنظمة قابلة للتوسّع من الفكرة إلى الإطلاق خلال أسابيع.",
    "hero.cta1": "تواصل معنا",
    "hero.cta2": "اطلب عرضًا",
    "hero.badge1": "استضافة داخلية أو سحابية",
    "hero.badge2": "تسجيل موحّد SSO",
    "hero.badge3": "عربي/إنجليزي",
    "hero.badge4": "CI/CD",

    // Value Props
    "valueProps.title": "لماذا تختار Cordoba AI",
    "valueProps.speed": "سرعة بلا تنازلات",
    "valueProps.speedDesc": "من الفكرة إلى الإصدار الأول خلال أسابيع بفضل عوامل الذكاء الاصطناعي والأتمتة.",
    "valueProps.quality": "جودة يمكنك الوثوق بها",
    "valueProps.qualityDesc": "مراجعات كود، تغطية اختبارات، بوابات CI/CD.",
    "valueProps.security": "أمن مُدمج",
    "valueProps.securityDesc": "SSO وصلاحيات وضبط أسرار وسجلات تدقيق.",
    "valueProps.scale": "قابلية توسّع عالية",
    "valueProps.scaleDesc": "تصميمات داخلية أو سحابية للأداء والموثوقية.",

    // Capabilities
    "capabilities.title": "ما نبنيه",
    "capabilities.digitalServices": "الخدمات الرقمية والبوابات",
    "capabilities.digitalServicesDesc": "سير العمل، النماذج، اتفاقيات مستوى الخدمة، المدفوعات الإلكترونية.",
    "capabilities.internalPlatforms": "المنصات الداخلية",
    "capabilities.internalPlatformsDesc": "الابتكار، الأداء، إدارة المحافظ/المشاريع، التدقيق، سير عمل الموارد البشرية.",
    "capabilities.dataAI": "البيانات والذكاء الاصطناعي",
    "capabilities.dataAIDesc": "لوحات المعلومات، مساعدي التعلم الآلي/الذكاء الاصطناعي التوليدي، الأتمتة مع وكلاء الذكاء الاصطناعي.",
    "capabilities.integrations": "التكاملات",
    "capabilities.integrationsDesc": "SAP، ESB/iPaaS، GRP/ERP، بوابات الدفع.",
    "capabilities.mobileWeb": "تطبيقات الموبايل والويب",
    "capabilities.mobileWebDesc": "متجاوبة، سهلة الوصول، ثنائية اللغة (عربي/إنجليزي).",

    // Process
    "process.title": "كيف نسلّم—بسرعة وأمان",
    "process.discover": "الاستكشاف",
    "process.discoverDesc": "تحديد النتائج، النطاق، المخاطر، والمتطلبات غير الوظيفية.",
    "process.design": "التصميم",
    "process.designDesc": "تدفّقات UX، معمارية الحل، ضوابط الأمان، عقود البيانات.",
    "process.build": "التنفيذ",
    "process.buildDesc": "سباقات متوازية يقودها مهندسون + عوامل ذكاء اصطناعي.",
    "process.assure": "التحقق",
    "process.assureDesc": "اختبارات جودة وأمان وأداء، واعتماد UAT.",
    "process.launch": "الإطلاق",
    "process.launchDesc": "خطة انتقال، مراقبة ومؤشرات، أدلّة التشغيل.",
    "process.evolve": "التطوير المستمر",
    "process.evolveDesc": "SLAs، تحسينات، وإدارة التغييرات.",

    // Outcomes
    "outcomes.title": "نتائج مهمة",
    "outcomes.subtitle": "إطارات تسليم مثبتة، أهداف موثوقية، ومكاسب سرعة حقيقية—دون المساس بالجودة.",
    "outcomes.kpi1": "4–8 أسابيع",
    "outcomes.kpi1Desc": "للإصدار الإنتاجي الأول",
    "outcomes.kpi2": ">99.9%",
    "outcomes.kpi2Desc": "أهداف التوفّر",
    "outcomes.kpi3": "أسرع 30–50%",
    "outcomes.kpi3Desc": "بفضل عوامل الذكاء الاصطناعي",
    "outcomes.quote": "ما بين الفكرة والإطلاق... ستة أسابيع فقط.\nوفّرت Cordoba AI ما يتجاوز الحلّ — قدّمت تجربة ابتكار ذكية غيّرت توقّعاتنا تمامًا.",
    "outcomes.quoteAuthor": "Chief Technology Officer",

    // Featured Engagements
    "engagements.title": "مشاريع مختارة",
    "engagements.learnMore": "اعرف المزيد",
    "engagements.portfolio": "سِياق",
    "engagements.portfolioDesc": "حوكمة محفظة المشاريع المؤسسية مع رؤية وتحكم في الوقت الفعلي.",
    "engagements.portfolioBullet1": "مواءمة الاستراتيجية، الأولويات وبوابات التمويل",
    "engagements.portfolioBullet2": "سجلات الصحة والمخاطر والقضايا مع سير العمل",
    "engagements.portfolioBullet3": "خرائط طريق متعددة البرامج ولوحات تنفيذية",
    "engagements.ticketing": "نظام التذاكر",
    "engagements.ticketingDesc": "تذاكر تقنية المعلومات/العمليات الحديثة مع اتفاقيات مستوى الخدمة والأتمتة وتقارير واضحة.",
    "engagements.ticketingBullet1": "سير عمل الحوادث وطلبات الخدمة والتغييرات",
    "engagements.ticketingBullet2": "سياسات اتفاقيات مستوى الخدمة والتصعيد والتكامل مع البريد/MS Teams",
    "engagements.ticketingBullet3": "قاعدة المعرفة والفئات والتحليلات جاهزة",
    "engagements.cms": "نظام CMS ذكي—من دون مطوّر",
    "engagements.cmsDesc": "حرّك المحتوى عبر عامل ذكاء اصطناعي—من دون مطوّر. سريع وآمن وقابل للتوسّع.",
    "engagements.cmsBullet1": "توليد صفحات ومكوّنات عبر الأوامر",
    "engagements.cmsBullet2": "قوالب وهوية ثابتة",
    "engagements.cmsBullet3": "صلاحيات وموافقات وSEO ونشر فوري",

    // CTA
    "cta.title": "ابدأ مشروعك مع Cordoba AI",
    "cta.description": "شاركنا أهدافك وسنقدّم خطة تسليم وجدولًا زمنيًا سريعًا.",
    "cta.button": "تواصل معنا",

    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "شاركنا أهدافك، وسنرسل لك خطة تنفيذ وجدولاً زمنياً.",
    "contact.badge1": "تثبيت محلي",
    "contact.badge2": "تسجيل موحد",
    "contact.badge3": "عربي/إنجليزي",
    "contact.badge4": "CI/CD",
    "contact.name": "الاسم الكامل",
    "contact.namePlaceholder": "اسمك",
    "contact.email": "البريد الوظيفي",
    "contact.emailPlaceholder": "you@company.com",
    "contact.organization": "الجهة",
    "contact.organizationPlaceholder": "الشركة / الجهة",
    "contact.phone": "الهاتف (اختياري)",
    "contact.phonePlaceholder": "+971 ...",
    "contact.projectType": "نوع المشروع",
    "contact.projectTypePlaceholder": "اختر واحداً",
    "contact.projectTypeOption1": "مدير المحفظة",
    "contact.projectTypeOption2": "نظام التذاكر",
    "contact.projectTypeOption3": "نظام إدارة المحتوى (منشئ بدون برمجة)",
    "contact.projectTypeOption4": "آخر",
    "contact.message": "الرسالة/الأهداف",
    "contact.messagePlaceholder": "ماذا تريد أن تبني أو تحسّن؟",
    "contact.attachment": "مرفق (اختياري)",
    "contact.attachmentHelper": "تحميل ملخص / طلب عرض (PDF، DOCX، ≤10MB)",
    "contact.consent": "أوافق على التواصل معي بشأن طلبي.",
    "contact.submit": "إرسال الرسالة",
    "contact.privacyNotice": "بالإرسال، فإنك توافق على سياسة الخصوصية الخاصة بنا.",
    "contact.successTitle": "شكراً—تم استلام طلبك.",
    "contact.successMessage": "سنرد خلال يوم عمل واحد.",
    "contact.referenceId": "الرقم المرجعي",
    "contact.infoTitle": "معلومات الاتصال",
    "contact.emailLabel": "البريد الإلكتروني",
    "contact.emailValue": "info@cordoba-ai.com",
    "contact.office": "المكتب",
    "contact.officeLocation": "شركة عن بُعد (غرينتش+4)",
    "contact.followUs": "تابعنا",
    "contact.businessHours": "ساعات العمل",
    "contact.weekdays": "الإثنين–الجمعة",
    "contact.weekdaysTime": "9:00 ص – 6:00 م (غرينتش+4)",
    "contact.weekend": "السبت–الأحد",
    "contact.weekendTime": "مغلق",

    // Footer
    "footer.company": "الشركة",
    "footer.about": "حول",
    "footer.careers": "الوظائف",
    "footer.contact": "اتصل بنا",
    "footer.privacy": "الخصوصية",
    "footer.terms": "الشروط",
    "footer.security": "الأمان",
    "footer.rights": "Cordoba AI - جميع الحقوق محفوظة.",
    "footer.language": "اللغة",

    // Portfolio Manager Page
    "portfolio.hero.title": "سِياق",
    "portfolio.hero.subtitle": "حوكمة محفظة المشاريع المؤسسية مع رؤية وتحكم في الوقت الفعلي.",
    "portfolio.hero.cta1": "اطلب عرضًا",
    "portfolio.hero.cta2": "احجز جلسة استكشاف",
    "portfolio.pillars.title1": "الاستراتيجية ← التسليم",
    "portfolio.pillars.desc1": "ربط OKRs والثيمات الاستراتيجية بالبرامج والمشاريع والفوائد.",
    "portfolio.pillars.title2": "حوكمة سريعة",
    "portfolio.pillars.desc2": "بوابات المراحل، DOA/RACI، وسجلات تغييرات جاهزة للتدقيق.",
    "portfolio.pillars.title3": "بيانات موثوقة",
    "portfolio.pillars.desc3": "مصدر واحد للحقيقة للجداول الزمنية والميزانيات والمخاطر والمؤشرات.",
    "portfolio.pillars.title4": "وضوح تنفيذي",
    "portfolio.pillars.desc4": "لوحات المعلومات التنفيذية وصحة المحفظة في عرض واحد.",
    "portfolio.features.title": "ما ستحصل عليه",
    "portfolio.features.planning": "تخطيط المحفظة",
    "portfolio.features.planningDesc": "استقبال الأفكار، نماذج التسجيل، الأولويات، بوابات التمويل.",
    "portfolio.features.control": "التحكم في البرامج/المشاريع",
    "portfolio.features.controlDesc": "المعالم، التبعيات، سجلات RAID، طلبات التغيير.",
    "portfolio.features.financials": "الماليات",
    "portfolio.features.financialsDesc": "CAPEX/OPEX، خطوط الأساس، التوقعات، تباين التكلفة.",
    "portfolio.features.benefits": "الفوائد والمؤشرات",
    "portfolio.features.benefitsDesc": "الأهداف مقابل الفعلي، تحقيق الفوائد، خريطة المبادرات.",
    "portfolio.features.resources": "الموارد",
    "portfolio.features.resourcesDesc": "الأدوار، السعة، خرائط التخصيص، عبء العمل.",
    "portfolio.features.reporting": "التقارير",
    "portfolio.features.reportingDesc": "لوحات معلومات قابلة للتكوين، تصدير (PDF/XLS)، إحاطات تلقائية.",
    "portfolio.integrations.title": "التكاملات",
    "portfolio.integrations.list": "SAP/Oracle/ERP • SSO (Entra ID/ADFS) • Email/Teams • مستودع البيانات/Power BI",
    "portfolio.howItWorks.title": "كيف يعمل",
    "portfolio.howItWorks.step1": "الاستكشاف والتكوين",
    "portfolio.howItWorks.step1Desc": "2-3 ورش عمل",
    "portfolio.howItWorks.step2": "استيراد وتخطيط البيانات",
    "portfolio.howItWorks.step2Desc": "المشاريع، الموارد، المؤشرات",
    "portfolio.howItWorks.step3": "الإطلاق والتدريب",
    "portfolio.howItWorks.step3Desc": "تجريبي ← مؤسسي",
    "portfolio.outcomes.title": "النتائج",
    "portfolio.outcomes.stat1": "أسرع 30-50%",
    "portfolio.outcomes.stat1Desc": "دورات التقارير",
    "portfolio.outcomes.stat2": "90% اعتماد",
    "portfolio.outcomes.stat2Desc": "خلال 8-12 أسبوع",
    "portfolio.outcomes.stat3": "تخفيض 25%",
    "portfolio.outcomes.stat3Desc": "في التأخير غير المخطط",
    "portfolio.useCases.title": "حالات الاستخدام",
    "portfolio.useCases.gov": "EPMO حكومي",
    "portfolio.useCases.strategy": "مكاتب الاستراتيجية",
    "portfolio.useCases.it": "IT PMO",
    "portfolio.useCases.capital": "المشاريع الرأسمالية",
    "portfolio.useCases.transformation": "برامج التحول",
    "portfolio.security.title": "الأمان والنشر",
    "portfolio.security.item1": "سحابة داخلية أو سيادية",
    "portfolio.security.item2": "SSO/MFA",
    "portfolio.security.item3": "وصول قائم على الأدوار",
    "portfolio.security.item4": "سجلات التدقيق",
    "portfolio.cta.title": "جاهز للحوكمة بثقة؟",
    "portfolio.cta.button": "تحدث مع خبير",
    "portfolio.faq.q1": "كيف تتعاملون مع DOA/RACI المعقد؟",
    "portfolio.faq.a1": "ندعم مصفوفات الموافقة متعددة المستويات، قواعد التفويض، وقوالب RACI مخصصة تتوافق مع إطار الحوكمة الحالي لديك.",
    "portfolio.faq.q2": "هل يمكننا الاحتفاظ بأداتنا الحالية والمزامنة؟",
    "portfolio.faq.a2": "نعم، نوفر موصلات API والمزامنة المجدولة لمعظم أدوات إدارة المشاريع، مما يسمح بالتشغيل المختلط أثناء الانتقال.",
    "portfolio.faq.q3": "كم من الوقت حتى الإطلاق؟",
    "portfolio.faq.a3": "يستغرق النشر التجريبي النموذجي 4-8 أسابيع بما في ذلك الاستكشاف والتكوين واستيراد البيانات وتدريب المستخدمين.",
    "portfolio.faq.q4": "هل تدعمون العربية وRTL؟",
    "portfolio.faq.a4": "نعم، الترجمة الكاملة للعربية وواجهة RTL متضمنة بشكل افتراضي.",
    "portfolio.faq.q5": "ما التقارير المتضمنة افتراضيًا؟",
    "portfolio.faq.a5": "لوحة صحة المحفظة، تقارير حالة المشروع، التباين المالي، استخدام الموارد، سجلات المخاطر، والإحاطات التنفيذية.",

    // Ticketing System Page
    "ticketing.hero.title": "نظام التذاكر",
    "ticketing.hero.subtitle": "تذاكر تقنية المعلومات/العمليات الحديثة مع SLAs والأتمتة وتقارير خدمة واضحة.",
    "ticketing.hero.cta1": "ابدأ تجريبي",
    "ticketing.hero.cta2": "شاهد عرضًا توضيحيًا",
    "ticketing.pillars.title1": "حل أسرع",
    "ticketing.pillars.desc1": "نماذج موجهة، توجيه تلقائي، واقتراحات ذكية.",
    "ticketing.pillars.title2": "لا SLAs فائتة",
    "ticketing.pillars.desc2": "سياسات، تقاويم، وتصعيدات متعددة المستويات.",
    "ticketing.pillars.title3": "قاعدة معرفة واحدة",
    "ticketing.pillars.desc3": "مقالات، فئات، وتحليلات الانحراف.",
    "ticketing.pillars.title4": "مبني للعمليات",
    "ticketing.pillars.desc4": "تدفقات التغيير والمشاكل، الموافقات، دعم CAB.",
    "ticketing.capabilities.title": "القدرات",
    "ticketing.capabilities.types": "أنواع التذاكر",
    "ticketing.capabilities.typesDesc": "حادث، طلب خدمة، مشكلة، تغيير.",
    "ticketing.capabilities.workflows": "سير العمل",
    "ticketing.capabilities.workflowsDesc": "نماذج الاستقبال، الحقول الديناميكية، الموافقات، قواعد التعيين.",
    "ticketing.capabilities.slas": "SLAs",
    "ticketing.capabilities.slasDesc": "الساعات، الإيقاف، العطلات، إشعارات الخرق، سياسات التصعيد.",
    "ticketing.capabilities.channels": "القنوات",
    "ticketing.capabilities.channelsDesc": "البوابة، تحليل البريد، MS Teams، API/webhooks.",
    "ticketing.capabilities.kb": "KB",
    "ticketing.capabilities.kbDesc": "تأليف المقالات، الإصدارات، التعليقات، البحث.",
    "ticketing.capabilities.analytics": "التحليلات",
    "ticketing.capabilities.analyticsDesc": "امتثال SLA، تقادم الأعمال المتراكمة، أداء الوكلاء، CSAT.",
    "ticketing.automation.title": "أمثلة الأتمتة",
    "ticketing.automation.ex1": "التعيين التلقائي بناءً على الفئة/التأثير",
    "ticketing.automation.ex2": "اقتراح مقالات KB للطالب/الوكيل",
    "ticketing.automation.ex3": "إغلاق التذاكر القديمة مع التذكيرات والضمانات",
    "ticketing.integrations.title": "التكاملات",
    "ticketing.integrations.list": "Entra ID/ADFS • البريد/SMTP • MS Teams • الأصول/CMDB (اختياري) • Webhooks",
    "ticketing.timeline.title": "الجدول الزمني للتنفيذ",
    "ticketing.timeline.week1": "الأسبوع 1-2: الاستكشاف والكتالوج",
    "ticketing.timeline.week2": "الأسبوع 3-4: سير العمل وSLAs",
    "ticketing.timeline.week3": "الأسبوع 5-6: التجريبي والتدريب",
    "ticketing.outcomes.title": "النتائج",
    "ticketing.outcomes.stat1": "أسرع 20-40%",
    "ticketing.outcomes.stat1Desc": "متوسط وقت الحل",
    "ticketing.outcomes.stat2": "أقل 30%",
    "ticketing.outcomes.stat2Desc": "إعادة فتح عبر نماذج وKB أفضل",
    "ticketing.outcomes.stat3": "تخفيض +50%",
    "ticketing.outcomes.stat3Desc": "في خروقات SLA",
    "ticketing.cta.title": "أصلح فوضى الخدمة—ابدأ بتجريبي مركّز",
    "ticketing.cta.button": "ابدأ تجريبي",
    "ticketing.faq.q1": "هل تنقلون التذاكر/KB القديمة؟",
    "ticketing.faq.a1": "نعم، نوفر أدوات وخدمات الترحيل لاستيراد التذاكر التاريخية والمرفقات ومقالات قاعدة المعرفة مع الحفاظ على العلاقات.",
    "ticketing.faq.q2": "كيف تعمل العطلات وساعات العمل في SLAs؟",
    "ticketing.faq.a2": "يمكنك تحديد تقاويم متعددة مع العطلات وساعات العمل. تتوقف ساعات SLA خارج ساعات العمل وتتكيف تلقائيًا مع العطلات الرسمية.",
    "ticketing.faq.q3": "هل يمكن للطالبين إرسال البريد مباشرة؟",
    "ticketing.faq.a3": "نعم، تحليل البريد الوارد ينشئ تذاكر تلقائيًا، والردود تتزامن بشكل ثنائي الاتجاه بين البريد والبوابة.",
    "ticketing.faq.q4": "هل تدعمون CAB/تقويم التغيير؟",
    "ticketing.faq.a4": "نعم، إدارة التغيير تتضمن تدفقات عمل CAB، اجتماعات الموافقة، نوافذ التعتيم، وتكامل التقويم.",
    "ticketing.faq.q5": "ما التحليلات القياسية؟",
    "ticketing.faq.a5": "معدلات امتثال SLA، اتجاهات حجم التذاكر، متوسط وقت الحل، تقادم الأعمال المتراكمة، عبء عمل الوكيل، ودرجات رضا العملاء.",

    // AI CMS Page
    "cms.hero.title": "نظام CMS ذكي (منشئ مواقع — بدون برمجة)",
    "cms.hero.subtitle": "أنشئ وانشر الصفحات باستخدام عامل ذكاء اصطناعي—بدون برمجة. آمن وقابل للتوسع وسريع.",
    "cms.hero.cta1": "جرّب المحرر",
    "cms.hero.cta2": "اطلب عرضًا موجهًا",
    "cms.pillars.title1": "أنشئ بالأوامر",
    "cms.pillars.desc1": "أقسام، صفحات، ووسائط في دقائق.",
    "cms.pillars.title2": "دائمًا على العلامة التجارية",
    "cms.pillars.desc2": "ثيمات، مكونات، وحواجز أسلوب.",
    "cms.pillars.title3": "نشر محكوم",
    "cms.pillars.desc3": "أدوار، موافقات، تدفقات مراجعة، تدقيق.",
    "cms.pillars.title4": "SEO مدمج",
    "cms.pillars.desc4": "بيانات وصفية، خرائط الموقع، وفحوصات أفضل الممارسات.",
    "cms.capabilities.title": "القدرات",
    "cms.capabilities.ai": "التحرير بالذكاء الاصطناعي",
    "cms.capabilities.aiDesc": "اقتراحات الكتل، إعادة الكتابة/التحسين، استخراج الملخصات.",
    "cms.capabilities.components": "المكونات",
    "cms.capabilities.componentsDesc": "Hero، شبكات الميزات، نطاقات CTA، FAQs، معارض، نماذج.",
    "cms.capabilities.media": "الوسائط",
    "cms.capabilities.mediaDesc": "تحسين الصور، نص بديل تلقائي، توصيل CDN.",
    "cms.capabilities.seo": "SEO",
    "cms.capabilities.seoDesc": "العناوين/الأوصاف، schema، canonical، خريطة الموقع، إعادة التوجيه.",
    "cms.capabilities.localization": "الترجمة",
    "cms.capabilities.localizationDesc": "عربي/إنجليزي، دعم RTL، تدفق الترجمة.",
    "cms.capabilities.publishing": "النشر",
    "cms.capabilities.publishingDesc": "المعاينة/المقارنة، تاريخ الإصدارات، التراجع الفوري.",
    "cms.templates.title": "القوالب",
    "cms.templates.gov": "بوابة خدمة حكومية",
    "cms.templates.corporate": "موقع مؤسسي",
    "cms.templates.campaign": "حملة/صفحة هبوط",
    "cms.security.title": "الأمان والوصول",
    "cms.security.item1": "SSO/MFA",
    "cms.security.item2": "أدوار (مؤلف، محرر، معتمد، مسؤول)",
    "cms.security.item3": "صلاحيات دقيقة",
    "cms.security.item4": "سجلات التدقيق",
    "cms.outcomes.title": "النتائج",
    "cms.outcomes.stat1": "أسرع 3-5×",
    "cms.outcomes.stat1Desc": "إطلاق صفحات جديدة",
    "cms.outcomes.stat2": "تخفيض 40-60%",
    "cms.outcomes.stat2Desc": "في تكلفة التطوير الخارجي",
    "cms.outcomes.stat3": "درجات محسنة",
    "cms.outcomes.stat3Desc": "Core Web Vitals افتراضيًا",
    "cms.cta.title": "ابنِ صفحتك التالية في دقائق",
    "cms.cta.button": "جرّب المحرر",
    "cms.faq.q1": "هل يمكننا استيراد موقعنا/ثيمنا الحالي؟",
    "cms.faq.a1": "نعم، يمكننا ترحيل الصفحات الموجودة وتكييف ثيم علامتك التجارية في مكتبة المكونات لدينا أثناء الإعداد.",
    "cms.faq.q2": "كيف تعمل الموافقات؟",
    "cms.faq.a2": "تحدد تدفقات الموافقة حسب الدور/نوع المحتوى. مسودة ← مراجعة ← اعتماد ← نشر، مع الإشعارات وأدوات المقارنة.",
    "cms.faq.q3": "هل يمكن للفرق غير التقنية إدارة العربية/RTL؟",
    "cms.faq.a3": "بالتأكيد. محرر الذكاء الاصطناعي ومعاينة RTL يعملان بسلاسة للمحتوى العربي دون الحاجة إلى معرفة تقنية.",
    "cms.faq.q4": "ماذا عن المكونات المخصصة؟",
    "cms.faq.a4": "يمكننا بناء مكونات مخصصة كجزء من الإعداد أو تدريب فريقك على توسيع المكتبة باستخدام SDK المكونات لدينا.",
    "cms.faq.q5": "هل تدعمون النشر الداخلي؟",
    "cms.faq.a5": "نعم، يمكن نشر CMS داخليًا أو في بيئات سحابية سيادية بنفس الميزات مثل SaaS السحابي.",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Check localStorage first
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && (saved === "en" || saved === "ar")) {
      setLanguageState(saved);
      updateHTMLAttributes(saved);
    } else {
      // Detect browser language
      const browserLang = navigator.language.toLowerCase();
      const detected = browserLang.startsWith("ar") ? "ar" : "en";
      setLanguageState(detected);
      updateHTMLAttributes(detected);
      localStorage.setItem("language", detected);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    updateHTMLAttributes(lang);
  };

  const updateHTMLAttributes = (lang: Language) => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Always provide the context, even during SSR
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
